record:
  repo_id: &repo_id "reponame/pick_place"
  debug: 0 # if True, robot will not execute any actions, but gripper can still be controlled
  user_notes:  # any additional notes about the dataset
  fps: 15 # dataset and camera frame rate

  teleop:
    use_gripper: &use_gripper True # shared gripper toggle (anchor referenced below)
    spacemouse_config:
      channel_signs: [-1, -1, 1, -1, -1, 1]
      use_gripper: *use_gripper # whether the spacemouse robot can use gripper
      pose_scaler: [0.02, 0.08] # scaler for spacemouse actions [position, attitude]

  robot:
    # ip: &ip "172.16.0.2" # robot ip
    ip: &ip "192.168.50.10" # NUC IP (runs Polymetis + server zerorpc:4242)
    use_gripper: *use_gripper
    close_threshold: 0.7 # threshold to determine gripper open/close
    gripper_bin_threshold: 0.98 # threshold to determine gripper is closed
    # gripper_port: &gripper_port "/dev/franka_left_gripper" # gripper_port
    gripper_reverse: false  # If gripper moves opposite, flip this value
    gripper_max_open: 0.085 # gripper max open width in meters 0.0801 for franka hand, 0.12 for robotiq gripper

  task:
    description: "Open the top drawer of the three-tier drawer." # task description
    num_episodes: 10 # number of episodes to record
    display: True # Whether to display the data during recording
    resume: False # whether to resume from an existing dataset
    # resume_dataset: rlco/pick_carrot_into_yellow_tray_episode_100_20260410_v01 # dataset to resume from if resume is True
  
  time:
    episode_time_sec: 6000 # max time per episode in seconds
    reset_time_sec: 6000 # max time to reset between episodes in seconds
    save_meta_period: 1 # Save metadata after every N episodes

  cameras:
    camera_type: "orbbec" # "realsense" or "orbbec"
    exterior_cam_id: "CPC936300041" # Orbbec serial or RealSense serial
    wrist_cam_id: "CPC93630001C" # Orbbec serial or RealSense serial
    width: 640 # 640 424
    height: 480 # 480 240

  storage:
    push_to_hub: False # whether to push the dataset to your huggingface repo after recording

replay:
  dataset_name: rlco/test_0612_20260612_v01 # 录制时自动生成的实际名称(repo_id+日期+版本)
  episode_idx: 0 # episode index to replay
  robot:
    ip: *ip

visualize:
  dataset_name: rlco/test_0612_20260612_v01 # 录制时自动生成的实际名称(repo_id+日期+版本)
  episode_index: 0 # episode index to visualize

